# Generated by Django 3.1 on 2020-08-05 03:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('device_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='data_key',
            field=models.CharField(max_length=50, verbose_name='DATA_KEY'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='data_val',
            field=models.TextField(verbose_name='DATA_VALUE'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='UID'),
        ),
    ]
